apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-api

spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30 
  selector:
    matchLabels:
      app: books-api
  template:
    metadata:
      labels:
        app: books-api
    spec:
      containers:
      - name: books-api
        image: ghcr.io/zorinivana/books-image:1.0.0
        env:
          - name: CONNECTION_STRING
            value: "Data Source=20.123.206.86;Initial Catalog=Books;User ID=TestAdmin;Password=Pa$$w0rD12345:"        
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 150m
