apiVersion: v1
kind: Service
metadata:
  name: books-api

spec:
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 80
    - port: 443
      name: https
      targetPort: 443
  selector:
    app: books-api
