apiVersion: v1
kind: Service
metadata:
  name: books-api

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
    - port: 443
      targetPort: 443
  selector:
    app: books-api
