name: Build and deploy package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ConsoleApp2/Dockerfile --tag ghcr.io/zorinivana/books-image:1.0.0
    - name: Login to registry
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login ghcr.io -u zorinivana --password-stdin     
    - name: Push image to registry
      run: docker push ghcr.io/zorinivana/books-image:1.0.0
    # Get the GKE credentials so we can deploy to the cluster
    - name: Login to GKE
      uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }} 
    # Set secret
    # - name: Set up secret
      #run: kubectl apply secret generic cn_str ${{ secrets.CONNECTION_STRING }}
    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize  
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        ./kustomize edit set image ghcr.io/zorinivana/books-image:1.0.0
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide         
    
      
