name: Build and deploy package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ConsoleApp2/Dockerfile --tag ghcr.io/zorinivana/books-image:1.0.0
    - name: Login to registry
      run: docker login -u zorinivana --password ${{ secrets.DOCKER_TOKEN }}
    - name: Push image to registry
      run: docker push ghcr.io/zorinivana/books-image:1.0.0
