apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: books-api

spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30 
  template:
    metadata:
      labels:
        app: books-api

    spec:
      containers:
      - name: books-api
        image: docker pull ghcr.io/zorinivana/books-image:1.0.0
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 150m
